### ISSUE TITLE
MockDocumentReference update() should throw error when document does not exist

### ISSUE THREAD

**Issue by lachiejames** [atn832/fake_cloud_firestore#152]
From the `cloud_firestore` docs:
![image](https://user-images.githubusercontent.com/47808687/114259645-ccbd9f00-9a12-11eb-9ec5-bddd1859d621.png)

The key phrase here being: `If no document exists yet, the update will fail.`

Following this logic, adding this test to `cloud_firestore_mocks_test.dart` should result in a success:
```
  test('updating document should throw error for non-existant IDs', () async {
    final firestore = MockFirestoreInstance();

    expect(
      () async => await firestore.collection('messages').doc('new ID').update({'user.counter': 5}),
      throwsA(isA<NoSuchMethodError>()),
    );
  });
```

But instead, it results in the following test failure:
```
Expected: throws <Instance of 'NoSuchMethodError'>
  Actual: <Closure: () => Future<void>>
   Which: returned a Future that emitted <null>

package:test_api                             expect
main.<fn>
test\cloud_firestore_mocks_test.dart:979
main.<fn>
test\cloud_firestore_mocks_test.dart:976
```

**Comment by TommyLCox** [comment]
Yes, the `update` method in the mock is currently acting like `set`. It creates the document if the document id does not exist. This does not match the docs for the Firestore update method. I assume that Firestore itself is behaving according to its own docs for `set` and `update`.
