### ISSUE TITLE
MockDocumentReference.set({}), then get() returns null

### ISSUE THREAD

**Issue by atn832** [atn832/fake_cloud_firestore#156]
This test fails.

```dart
await instance.collection('users').doc('3').set({});
final doc = await instance.collection('users').doc('3').get();
expect(doc.data(), isNotNull);
```

I'll have to try it on the actual Firestore to see how it should behave.

**Comment by atn832** [comment]
If this is indeed a bug, we should revert the changes in https://github.com/atn832/cloud_firestore_mocks/pull/153/files#diff-9d69ed340c3ab50d969a5011a19f493ade18a72981f8bef6e8a2a878e3820d9e back to `set({})`.

**Comment by jibbers42** [comment]
I just starting using this package and ran into the same issue. I'm curious if you ever verified Firestore behavior - I haven't, but it does feel like this should work.

**Comment by atn832** [comment]
https://pub.dev/packages/fake_cloud_firestore/changelog#249
