### ISSUE TITLE
Support for query.startAt and query.endAt for non-exact matches

### ISSUE THREAD

**Issue by atn832** [atn832/fake_cloud_firestore#167]
As of #151, we support only exact matches.

**Comment by cedvdb** [comment]
related https://github.com/atn832/fake_cloud_firestore/pull/216 https://github.com/atn832/fake_cloud_firestore/pull/215

**Comment by atn832** [comment]
Fixed by https://github.com/atn832/fake_cloud_firestore/pull/216.
