### ISSUE TITLE
Implement withConverter

### ISSUE THREAD

**Issue by felixwortmann** [atn832/fake_cloud_firestore#171]
The `.withConverter()` method should be supported. It is the intentional way to parse your data from map to object in firestore now. <br>

Missing in [this](https://github.com/atn832/cloud_firestore_mocks/blob/master/lib/src/mock_document_reference.dart) file in line 211 and following.
<br>
Thanks a lot for this great library.

**Comment by atn832** [comment]
Published at https://pub.dev/packages/fake_cloud_firestore/changelog#101.

**Comment by atn832** [comment]
Oh you're right, I forgot to support that case. Filed #175.

**Comment by atn832** [comment]
Would you mind trying again? https://pub.dev/packages/fake_cloud_firestore/changelog#102

**Comment by felixwortmann** [comment]
Works now, thanks a lot
