### ISSUE TITLE
Removing a document invokes `fromFirestore` from the `withConverter`

### ISSUE THREAD

**Issue by wesleyfuchter** [atn832/fake_cloud_firestore#191]
Hey there!

Just want to say this package is helping a lot during my learning on how to test a Firestore service.

I'm using `fake_cloud_firestore` to unit test a service class that removes a document. Here is the removing code:

```
 @override
  Future<void> remove(String id) async {
      await _tasksCollection.doc(id).delete();
  }
```

I'm using a converter to convert from JSON to my entity `Task` as:

```
class TaskFirestoreAdapter implements FirestoreAdapter<Task> {
  final _logger = Logger();

  @override
  Task fromFirestore(DocumentSnapshot<Map<String, dynamic>> document, _) {
    _logger.i('Parsing firestore document ${document.id} to task');    
    return Task.fromJson(document.id, document.data()!);
  }

  @override
  Map<String, Object?> toFirestore(Task model, _) {
    _logger.i('Parsing task ${model.id} to firestore document');
    return model.toJson();
  }
}
```

And here is my test:

```
test('Should remove a given task with its id', () async {
  final taskService = getIt<TaskService>();
  final query = await instance.collection('tasks').where('title', isEqualTo: 'Task 1').get();
  expect(query.docs.isEmpty, isFalse);
  await taskService.remove(query.docs.first.id);
  final queryAfterRemoving = await instance.collection('tasks').where('title', isEqualTo: 'Task 1').get();
  expect(queryAfterRemoving.docs.isEmpty, isTrue);
});
```

When I run this test I get the following error:

```
flutter test test/task_service_test.dart --name "Should remove a given task with its id"
00:02 +0: TaskService Should remove a given task with its id
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
00:02 +0 -1: TaskService Should remove a given task with its id [E]
  Null check operator used on a null value
  package:flutter_testing_experiment/src/core/services/task_firestore_adapter.dart 13:54  TaskFirestoreAdapter.fromFirestore
  package:fake_cloud_firestore/src/mock_document_reference.dart 204:52                    MockDocumentReference.get
  package:fake_cloud_firestore/src/mock_document_reference.dart 233:40                    MockDocumentReference.fireSnapshotUpdate
  package:fake_cloud_firestore/src/mock_document_reference.dart 219:5                     MockDocumentReference.delete
  package:flutter_testing_experiment/src/core/services/task_service.dart 49:36            TaskService.remove
  test/task_service_test.dart 75:25                                                       main.<fn>.<fn>
00:02 +0 -1: Some tests failed.
```

During the remove situation, `document.data()` returns null on my converter `fromFirestore` where I'm using `!` to avoid null complains from the compiler and it results on the error. The interesting part is that we can see the adapter being called on the remove situation, which I don't understand why.

By looking the code, this line is calling the converter: https://github.com/atn832/fake_cloud_firestore/blob/275d74bffb5cb6db89dd188e44451e87bb4d1339/lib/src/mock_document_reference.dart#L205

Does anyone has any idea how to solve this problem or workaround it if its something to be fixed?

Thanks folks!!

**Comment by atn832** [comment]
Thanks for reporting the issue!

When the document is deleted, it notifies listeners by firing an event with the snapshot. Since the document is deleted, we want to fire a snapshot with no data. There was indeed an issue where before firing the null data, it still called on the converter. I just merged #209 to fix that.

Removing the firing of the update introduced a regression (#196), so I restored the firing back (#208). I also wrote unit tests with and without converters to make sure everything works.
