### ISSUE TITLE
Upgrade to be compatible with cloud_firestore 3.1.0

### ISSUE THREAD

**Issue by andre-paraense** [atn832/fake_cloud_firestore#193]
Because fake_cloud_firestore >=1.1.0 depends on cloud_firestore ^2.2.0 and `project` depends on cloud_firestore 3.1.0, fake_cloud_firestore >=1.1.0 is forbidden.
So, because `project` depends on fake_cloud_firestore 1.1.3, version solving failed.

**Comment by atn832** [comment]
Thanks for reporting the issue. This should have been fixed by #190 since 1.2.0.
