### ISSUE TITLE
Document removal no longer notifies on StreamSubscription<DocumentSnapshot> since 1.2.0

### ISSUE THREAD

**Issue by labrom** [atn832/fake_cloud_firestore#196]
`Stream<DocumentSnapshot>.listen()` used to notify when the document is deleted in version 1.1.3.
It no longer does it in version 1.2.0.

**Comment by kinex** [comment]
This looks like a bug, it broke my unit tests.

**Comment by atn832** [comment]
Thanks for reporting. It's fixed now and released as version 1.2.1. https://pub.dev/packages/fake_cloud_firestore/changelog#121

Ideally I should have reverted the offending commit and re-released a quick patch, but didn't have the time to. In case a regression happens again and I can't fix it fast, the best way to work around it is to set your dependency to fake_firestore_to the latest working version in pubspec.yaml:
```yaml
fake_cloud_firestore: 1.1.3
```
