### ISSUE TITLE
Implement MockQuery.endBeforeDocument

### ISSUE THREAD

**Issue by dhruvd0** [atn832/fake_cloud_firestore#199]
Calling MockQuery.endBeforeDocument throws:

`  UnimplementedError
  package:fake_cloud_firestore/src/mock_query.dart 339:5                        MockQuery.endBeforeDocument`

Plugin Version: ` fake_cloud_firestore 1.2.0  `

**Comment by atn832** [comment]
Thanks for reporting the issue. It has been fixed by #197.
