### ISSUE TITLE
Support for endAtDocument, endBefore, endBeforeDocument and startAtDocument

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [atn832/fake_cloud_firestore#211]
I found this library very useful but it was just missing some query modifiers: endAtDocument, endBefore, endBeforeDocument and startAtDocument
And I needed them in my tests so I implemented them in this pr #197

**Comment by atn832** [comment]
Hi @Andrew-Bekhiet, thank you for contributing! I took a look at your PR and it looks good. I'll review it more closely by the end of next week and submit it if all is well.
