### ISSUE TITLE
Incompatibility between fake_cloud_firestore and cloud_firestore version 3.4

### ISSUE THREAD

**Issue by goneall** [atn832/fake_cloud_firestore#231]
When running my unit tests with fake_cloud_firestore version 1.2.4 and cloud_firestore version 3.4 or above, I'm getting the following compile errors:

```
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/fake_cloud_firestore-1.2.4/lib/src/fake_cloud_firestore_instance.dart:76:13: Error: The method 'FakeFirebaseFirestore.runTransaction' has fewer named arguments than those of overridden method 'FirebaseFirestore.runTransaction'.
  Future<T> runTransaction<T>(TransactionHandler<T> transactionHandler,
            ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.4.2/lib/src/firestore.dart:219:13: Context: This is the overridden method ('runTransaction').
  Future<T> runTransaction<T>(
```

This can be worked around by restricting the version of cloud_firestore to 3.3.

In testing various versions of cloud_firestore, it looks like this was introduced in version 3.4.0.

**Comment by atn832** [comment]
Thanks for reporting. I changed the signature to match that of firestore 3.4.0 and released an update: https://pub.dev/packages/fake_cloud_firestore/changelog#130.

**Comment by goneall** [comment]
Thanks @atn832 for the quick response.  I updated to the latest and everything's working great.
