### ISSUE TITLE
FieldValue.arrayRemove doesn't work when using List of maps

### ISSUE THREAD

**Issue by volkankahraman** [atn832/fake_cloud_firestore#234]
There are two lists that we use one is a list of strings and the other one is a list of maps
```dart
String eventId = "1";
Map<String, dynamic> attendance = { "id": "1"};

await fakeFirestore.collection('events').doc(eventId).update({
    'attendanceIdList': FieldValue.arrayRemove([attendanceId]),
    'attendanceList': FieldValue.arrayRemove([attendance]),
});
```
This code is removing the `attendanceId` from `attendanceIdList` but it is not working when we remove `attendance` map from the list. Even though they are same as the collection

**Comment by atn832** [comment]
Fixed by #237 and released at  https://pub.dev/packages/fake_cloud_firestore/changelog#132.
