### ISSUE TITLE
Add support for mocking server timestamp

### ISSUE THREAD

**Issue by AndrasTimar** [atn832/fake_cloud_firestore#238]
I would like to propose the use of the clock package, which would make it possible to mock the server timestamp. Now the code uses Timestamp.now(), which in return uses DateTime.now(), which can not be changed from the outside.

**Comment by ming-chu** [comment]
Hi @AndrasTimar , would you mind share more information about the `clock package`?

**Comment by AndrasTimar** [comment]
> Hi @AndrasTimar , would you mind share more information about the `clock package`?

Sure, you can read about it here: https://pub.dev/packages/clock

**Comment by atn832** [comment]
That sounds great! Would you be able to contribute a PR for it?

**Comment by ming-chu** [comment]
I created a PR for this.
https://github.com/atn832/fake_cloud_firestore/pull/287

Sorry, I am late........very late.

**Comment by atn832** [comment]
Thanks to @ming-chu for implementing this. I just published it to https://pub.dev/packages/fake_cloud_firestore/changelog#246.
