### ISSUE TITLE
Migrate example to Android embedding v2

### ISSUE THREAD

**Issue by Zohenn** [atn832/fake_cloud_firestore#242]
This would prevent some of the checks from failing.

**Comment by atn832** [comment]
Strange that we're still getting the error. I thought I had already done that at https://github.com/atn832/fake_cloud_firestore/commit/dd9231fd2d16d065c1a3ff4f0af3b3c538d2c682. But maybe I should have updated example/android instead?

**Comment by Zohenn** [comment]
Yes, there are additional changes to be made in AndroidManifest.xml, specifically point 5 here https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration.

I will look into that and see if there are no additional warnings related to old splash screen implementation.
