### ISSUE TITLE
Support for .count() function

### ISSUE THREAD

**Issue by Seyun** [atn832/fake_cloud_firestore#244]
The feature of counting documents with O(1) has been released as the following document describes. 

https://firebase.google.com/docs/firestore/query-data/aggregation-queries

It would be super helpful if fake cloud firestore adds this one too.

**Comment by atn832** [comment]
Exciting news, thanks for letting me know. I just implemented it and released it to https://pub.dev/packages/fake_cloud_firestore/changelog#2001.
