### ISSUE TITLE
Issue on Firestore 4.4.0

### ISSUE THREAD

**Issue by sydneyagcaoili** [atn832/fake_cloud_firestore#265]
Hello, I am getting this error and it fails most of our tests.

`../../.pub-cache/hosted/pub.dev/fake_cloud_firestore-2.3.0+3/lib/src/mock_query.dart:125:34: Error: The parameter 'values' of the
method 'MockQuery.startAt' has type 'List<dynamic>', which does not match the corresponding type, 'Iterable<Object?>', in the
overridden method, 'Query.startAt'.
 - 'List' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Iterable<Object?>', or, for a covariant parameter, a subtype.
  Query<T> startAt(List<dynamic> values) => _subQueryByKeyValues(
                                 ^
../../.pub-cache/hosted/pub.dev/cloud_firestore-4.4.0/lib/src/query.dart:138:12: Context: This is the overridden method
('startAt').
  Query<T> startAt(Iterable<Object?> values);
           ^
../../.pub-cache/hosted/pub.dev/fake_cloud_firestore-2.3.0+3/lib/src/mock_query.dart:134:32: Error: The parameter 'values' of the
method 'MockQuery.endAt' has type 'List<dynamic>', which does not match the corresponding type, 'Iterable<Object?>', in the
overridden method, 'Query.endAt'.
 - 'List' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Iterable<Object?>', or, for a covariant parameter, a subtype.
  Query<T> endAt(List<dynamic> values) => _subQueryByKeyValues(
                               ^
../../.pub-cache/hosted/pub.dev/cloud_firestore-4.4.0/lib/src/query.dart:49:12: Context: This is the overridden method ('endAt').
  Query<T> endAt(Iterable<Object?> values);
           ^
../../.pub-cache/hosted/pub.dev/fake_cloud_firestore-2.3.0+3/lib/src/mock_query.dart:228:22: Error: The parameter
'arrayContainsAny' of the method 'MockQuery.where' has type 'List<dynamic>?', which does not match the corresponding type,
'Iterable<Object?>?', in the overridden method, 'Query.where'.
 - 'List' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Iterable<Object?>?', or, for a covariant parameter, a subtype.
      List<dynamic>? arrayContainsAny,
                     ^
../../.pub-cache/hosted/pub.dev/cloud_firestore-4.4.0/lib/src/query.dart:151:12: Context: This is the overridden method ('where').
  Query<T> where(
           ^
../../.pub-cache/hosted/pub.dev/fake_cloud_firestore-2.3.0+3/lib/src/mock_query.dart:229:22: Error: The parameter 'whereIn' of the
method 'MockQuery.where' has type 'List<dynamic>?', which does not match the corresponding type, 'Iterable<Object?>?', in the
overridden method, 'Query.where'.
 - 'List' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Iterable<Object?>?', or, for a covariant parameter, a subtype.
      List<dynamic>? whereIn,
                     ^
`

I am keen to contributing to a fix but not until a week later due to my current workload/headspace.

**Comment by tbz43353** [comment]
Seeing the same problem.

**Comment by atn832** [comment]
Thank you so much for fixing the issue quickly @sydneyagcaoili. I just published your fix to version 2.4.0. https://pub.dev/packages/fake_cloud_firestore/changelog#240.
