### ISSUE TITLE
Support for flutter web

### ISSUE THREAD

**Issue by desimmons** [atn832/fake_cloud_firestore#267]
When running tests against a web-based platform, e.g., `chrome`, the instantiation of `FakeFirebaseFirestore()` appears to be blocking and ultimately causes the tests to timeout and fail.

To reproduce this, from the root of this repository:
```
flutter test --verbose --platform chrome
```

**Comment by atn832** [comment]
Thanks, it seems like there was some issue with cel, which fake_cloud_firestore indirectly depends on. I fixed cel and published an update. So if you run `flutter pub upgrade`, it should transitively install the latest version of cel, and it should fix the issue.

[Related ticket](https://github.com/atn832/fake_firebase_security_rules/issues/1).
