### ISSUE TITLE
Support for Firestore OR queries

### ISSUE THREAD

**Issue by giovanidebiagi** [atn832/fake_cloud_firestore#293]
Hi!

I couldn't find any documentation or issues regarding support for Firestore OR queries using `Filter.or()`. Does fake_cloud_firestore have it already?

https://firebase.google.com/docs/firestore/query-data/queries#or_queries

Thank you for the amazing package!

**Comment by gradycsjohnson** [comment]
The answer appears to be no. Whenever I use one I get an Unsupported error. 

Does anyone know if there's a plan to support this in the future?

**Comment by atn832** [comment]
If it's not in the documentation and does not work, it usually means it hasn't been implemented. Unfortunately I don't have the time to develop new features. However if someone is willing to tackle it, I always make an effort to review pull requests and release contributors' code.
