### ISSUE TITLE
Option to bypass security rules

### ISSUE THREAD

**Issue by cameron1024** [atn832/fake_cloud_firestore#317]
Hi, firstly thanks for the useful library!

I've recently tried adding security rules to my tests, and have found that they fail because I start the test by injecting some fake data, and I wasn't able to see how I could access the database without checking security rules.

Ideally, I'd be able to call something like:
```dart
final fake = FakeFirebaseFirestore(
  auth: mockAuth.authForFakeFirestore,
  securityRules: "...",
);

fake.bypassingSecurityRules.collection("forbidden").doc().insert(...);

// later in the test
fake.collection("forbidden").doc().insert(...);  // fails because of security rules
```
Is something like this possible? I had a look through the docs and the API surface, and couldn't find anything that looked like it could do this.

Thanks :pray:

**Comment by atn832** [comment]
If we expose a setter for security rules, you could do something like this:
```dart
import 'package:fake_firebase_security_rules/fake_firebase_security_rules.dart';

// Setting no security rules will by default allow everything.
// See https://github.com/atn832/fake_cloud_firestore/blob/c5548ce2f6405eb7f7a2a8a823edf15fbc3681cc/lib/src/fake_cloud_firestore_instance.dart#L46
final fake = FakeFirebaseFirestore(
  auth: mockAuth.authForFakeFirestore,
);

// Write data without restriction.
fake.collection("forbidden").doc().insert(...);

// Set up security rules.
fake.securityRules = FakeFirebaseSecurityRules('''
// actual rules
''');

// later in the test
fake.collection("forbidden").doc().insert(...);  // fails because of security rules
```
What do you think?

**Comment by cameron1024** [comment]
Sounds like it would work perfectly, and more flexible than the API I suggested, thanks 😁

**Comment by atn832** [comment]
Thanks for the feedback. I just released this change to https://pub.dev/packages/fake_cloud_firestore/changelog#303. Usage is as we discussed: https://github.com/atn832/fake_cloud_firestore?tab=readme-ov-file#resetting-security-rules
