### ISSUE TITLE
Consider renaming the libraries

### ISSUE THREAD

**Issue by atn832** [atn832/fake_cloud_firestore#34]
As @suztomo pointed out in #26, those libraries are more fakes than mocks. Consider renaming the libraries to reflect that.

Source:
* https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da
* https://martinfowler.com/articles/mocksArentStubs.html

**Comment by atn832** [comment]
The steps would be:

1. publish a last update on the old pub.dev project to mention it's deprecated, and include a link to the new project, as per https://github.com/dart-lang/sdk/issues/12094.
2. rename the classes from *Mock to Fake*, eg from `FirestoreMock` to `FakeFirestore`. In this repo there's only 9 of them. There are even fewer in the other projects.
3. update the yaml and publish under the new name. Bump the version up to notify of the API change.
4. rename the GitHub repository.

Rinse and repeat for all 4 libraries, then finally update blog posts or GitHub comments with the new urls.

Since most of these steps are mostly administrative and don't require coding, I'll do them all myself.

@suztomo what do you think of this process?

**Comment by suztomo** [comment]
I would do the followings (I have never published a library in pub.dev):

1. Fork (not rename) GitHub repository with new name.
2. In new repo, rename the class from Mock to Fake ...
3. In new repo, update yaml and publish ...
4. With the old repo, publish a last update ...
5. Archive the old repo. This old GitHub repository serves to redirect users to new repository.

**Comment by atn832** [comment]
It turns out, renaming the repository is much more powerful than I thought. It will also handle web redirections and even git push redirects. So I can safely rename the repo.

https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by suztomo** [comment]
Nice. Good to know. Thanks.

**Comment by atn832** [comment]
Renamed this repository, discontinued the old package and published the new one at https://pub.dev/packages/fake_cloud_firestore.

**Comment by suztomo** [comment]
Thank you.

**Comment by atn832** [comment]
Thank you for your advice :)
