### ISSUE TITLE
UpdateData should throw PlatformException if no existing document

### ISSUE THREAD

**Issue by suztomo** [atn832/fake_cloud_firestore#40]
As in the #39 's test case, updateData should throw PlatformException if there's no document.

https://github.com/atn832/cloud_firestore_mocks/pull/39/files#diff-bc4857fb99d367ed497ed395a5dfa274R98

```
flutter: 00:01 +7 -2: Firestore behavior comparison: Nested objects update (Cloud Firestore) [E]
flutter:   PlatformException(Error 5, FIRFirestoreErrorDomain, No document to update:
projects/flutter-firestore/databases/(default)/documents/messages/UYK7FkXENdf7mshYHrjR)
```

**Comment by atn832** [comment]
Published to https://pub.dev/packages/fake_cloud_firestore/changelog#124.
